Only make a connection to the DB if necessary
3YOURMIND/django-migration-linter pull request #255
Opened 2023-05-09 06:32 UTC by mjvankampen

When updating to Django 4 I noticed that suddenly our CI failed as there was no valid database while linting migrations. This change will only connect to a DB when it is necessary (i.e. check only applied or unapplied migrations). That way you don't have to do trickery in your settings file when you run the linter without a DB.

2023-05-09 07:57 UTC, mjvankampen commented
Ah sorry not related to Django4 but still I think this PR is valid.

2023-07-02 07:24 UTC, David-Wobrock requested changes
Hey @mjvankampen ! Thanks for contributing and taking interest in the project 🙇 

I'm not sure I get the rationale behind this change 🤔
We still require a DB connection even when we don't specify only applied or unapplied migrations. The `MigrationLoader` object is still required to load and lint migrations.
I'm not sure it can work with this new condition.

Do you have more context/information about your case? :)

2023-07-15 11:17 UTC, mjvankampen commented
Sorry I’m somewhat new to databases and Django (coming from an embedded environment). While setting up CI/CD I noticed that to lint migrations you need to connect to the database. On a higher level I don’t really understand that as you don’t need to know the current state of the database as that is captured in your migrations already. Except if you only want to lint unapplied migrations for example.

From your reply the MigrationLoader is needed to lint the migrations and the MigrationLoader needs a connection to a database (the state of the db does not matter?) which is I guess hard to get around.

Please let me know if I understand correctly, then I’ve learned something and will work around it (like spin up a DB for linting).

2025-03-30 17:20 UTC, David-Wobrock commented
Hey @mjvankampen 

(better a late answer than no answer 😇 )

Of course, I understand the natural thought of "why should linting require a database? Since it only checks the SQL generated by the framework".

This linter project actually started with this thought, but it's an incorrect assumption to expect that Django generates the SQL for migrations "offline".
Django requires a reachable database to generate the SQL. See the Django [ticket-26624](https://code.djangoproject.com/ticket/26624) for the case of `index/unique_together`, where Django fetches the constraint name from database in order to generate the right SQL statement (leading to a bunch of bugs when using Django :/)

Thus the django migration linter became a fully-fledged Django application, so that it can leverage the "native" Django mechanism, including opening the database connection (implicitly by calling `sqlmigrate`).

---

An alternative approach for the linter was to lint the Django migrations.py files themselves, and not the SQL statements.
This would indeed not require a database, but simple access to the files of the project.
But it brings other sets of challenges (properly support other libraries, migrations have different behaviour depending on the databases, etc). :)

---

That being said, I'm super happy that the linter helped you catch some bugs :)
I'll close the PR for now, as I don't think we can avoid opening a DB connection, but feel free to re-open it.

2025-03-30 17:20 UTC, closed without merging